from .main import main_bp
from .auth import auth_bp
from .clientes import clientes_bp
from .servicios import servicios_bp
from .tecnicos import tecnicos_bp
from .usuarios import usuarios_bp
from .solicitudes import solicitudes_bp
from .asignaciones import asignaciones_bp
from .partes import partes_bp
from .facturas import facturas_bp
from .reportes import reportes_bp
from .admin import admin_bp
from .tecnico import tecnico_bp
